project:
  type: book

book:
  title: "Guía práctica de ChatGPT"
  subtitle: "Uso profesional para docencia, investigación y desarrollo"
  author: "Cristian Narváez"
  language: es
  date: "2025"
  chapters:
    - index.qmd
    - part: "Fundamentos de ChatGPT"
      chapters:
        - 01-introduccion.qmd
        - 02-que-es-chatgpt.qmd
        - 03-configuracion-basica.qmd

    #- part: "Dominar el arte del Prompting"
    #  chapters:
    #    - 04-fundamentos-prompting.qmd
    #    - 05-patrones-de-prompts.qmd
    #    - 06-mejorar-respuestas.qmd

    #- part: "Casos de uso por perfil"
    #  chapters:
    #    - 07-docencia.qmd
    #    - 08-investigacion-academica.qmd
    #    - 09-programacion-devops.qmd
    #    - 10-productividad-personal.qmd

    #- part: "Uso responsable, límites y ética"
    #  chapters:
    #    - 11-limitaciones.qmd
    #    - 12-privacidad.qmd
    #    - 13-uso-etico-academico.qmd

    #- part: "Taller práctico y plantillas"
    #  chapters:
    #    - 14-plantillas-prompts.qmd
    #    - 15-mini-proyectos.qmd
    #    - 16-checklist-final.qmd
    
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    toc: true
    number-sections: true
  
  pdf:
    documentclass: scrreprt

editor: visual

